# Generated by Django 3.2.4 on 2021-07-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('CountryLE', models.TextField(db_column='CountryLE')),
                ('Year', models.TextField(db_column='Year')),
                ('LifeEx', models.TextField(blank=True, db_column='LifeEx')),
                ('dummyID', models.IntegerField(db_column='dummyID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LifeExpectancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Populations',
            fields=[
                ('CountryNamePop', models.TextField(db_column='CountryNamePop')),
                ('Year', models.TextField(db_column='Year')),
                ('Population', models.TextField(blank=True, db_column='Population')),
                ('dummyID', models.IntegerField(db_column='dummyID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Populations',
                'managed': False,
            },
        ),
    ]
